Task-Mangement-Web/Controllers/AuthController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Reflection;
using System.Security.Claims;
using System_Utility;
using Task_mangement_Web.Models;
using Task_mangement_Web.Models.Dto;
using Task_Mangement_Web.Services;
using Task_Mangement_Web.Services.IServices;

namespace Task_Mangement_Web.Controllers
{
	public class AuthController : Controller
	{
		private readonly IAuthService _authService;
		private readonly IMapper _mapper;

        public AuthController(IAuthService authService,IMapper mapper)
        {
            _authService = authService;
			_mapper = mapper;
        }
		[HttpGet]
		public IActionResult Login()
		{
			LoginRequestDto obj = new LoginRequestDto();
			return View(obj);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Login(LoginRequestDto obj)
		{
			APIResponse response = await _authService.LoginAsync<APIResponse>(obj);
			if(response != null && response.IsSuccess)
			{
				LoginResponseDto model = JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(response.Result));

				var handler = new JwtSecurityTokenHandler();
				var jwt = handler.ReadJwtToken(model.Token);

				var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

				identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == "unique_name").Value));
				identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));
				var principal = new ClaimsPrincipal(identity);
				await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

				HttpContext.Session.SetString(SD.SessionToken,model.Token);
				return RedirectToAction("Index", "Home");
			}
			else
			{
				if (response == null || !response.IsSuccess)
				{
					ModelState.AddModelError("CustomError", "User Name or Password is incorrect");
				}
				else
				{
					ModelState.AddModelError("CustomError", response.Errors.FirstOrDefault());
				}
				return View(obj);
			}
		}
		[HttpGet]
		public IActionResult Register()
		{
			List<string> roles = new List<string>() { "User" };
			ViewBag.SelectList = new SelectList(roles);
			RegisterationRequestDto obj = new RegisterationRequestDto();
			return View(obj);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Register(RegisterationRequestDto obj)
		{
            if (!ModelState.IsValid)
            {
                // Return the view with the current model, so errors can be displayed
                return View(obj);
            }
            APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);
			if(result != null || result.IsSuccess)
			{
				return RedirectToAction("Login");
			}
			return View();
		}
		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();
			HttpContext.Session.SetString(SD.SessionToken,"");
			return RedirectToAction("Index", "Home");
		}
		public IActionResult AccessDenied()
		{
			return View();
		}

	}
}

Task-Mangement-Web/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System_Utility;
using Task_mangement_Web.Models;
using Task_mangement_Web.Models.Dto;
using Task_Mangement_Web.Services.IServices;

namespace Task_Mangement_Web.Controllers
{
    [Authorize(Roles = "admin,User")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IActionResult> IndexCategory()
        {
            List<CategoryDto> list = new();
            var response = await _categoryService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if(response != null&& response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CategoryDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
		public async Task<IActionResult> CreateCategory()
		{
            return View();
		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateCategory(CategoryDto categoryDto)
		{
            if (ModelState.IsValid)
            {
				var response = await _categoryService.CreateAsync<APIResponse>(categoryDto,HttpContext.Session.GetString(SD.SessionToken));
				if (response != null && response.IsSuccess)
				{
                    TempData["success"] = "Category created successfully";
                    return RedirectToAction("IndexCategory");
				}
			}
			TempData["error"] = "Error";
			return View(categoryDto);
		}
        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            var response = await _categoryService.GetAsync<APIResponse>(id,HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<CategoryDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteCategory(CategoryDto categoryDto)
        {
            var response = await _categoryService.DeleteAsync<APIResponse>(categoryDto.Id,HttpContext.Session.GetString(SD.SessionToken));
            if(response != null && response.IsSuccess)
            {
				TempData["success"] = "Category deleted successfully";
				return RedirectToAction("IndexCategory");
            }
			TempData["error"] = "Error";
			return View(categoryDto);
        }

		[HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateCategory(int id)
		{
			var response = await _categoryService.GetAsync<APIResponse>(id,HttpContext.Session.GetString(SD.SessionToken));
			if (response != null && response.IsSuccess)
			{
				var model = JsonConvert.DeserializeObject<CategoryDto>(Convert.ToString(response.Result));
				return View(model);
			}
			return NotFound();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateCategory(CategoryDto categoryDto)
		{
            if (ModelState.IsValid)
            {
				APIResponse response = await _categoryService.UpdateAsync<APIResponse>(categoryDto,HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
					TempData["success"] = "Category updated successfully";
					return RedirectToAction("IndexCategory");
                }
            }
            TempData["error"] = "Error";
			return View(categoryDto);
		}

	}
}

Task-Mangement-Web/Controllers/TaskController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System_Utility;
using Task_mangement_Web.Models;
using Task_mangement_Web.Models.Dto;
using Task_Mangement_Web.Models.Dto;
using Task_Mangement_Web.Services;
using Task_Mangement_Web.Services.IServices;

namespace Task_Mangement_Web.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ITaskService _taskService;
        private readonly IMapper _mapper;
        public TaskController(ITaskService taskService,ICategoryService categoryService, IMapper mapper)
        {
            _taskService = taskService;
            _categoryService = categoryService;
            _mapper = mapper;

        }
        public async Task<IActionResult> Index()
        {
            List<TaskDto> list = new();
            var response = await _taskService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<TaskDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        [HttpGet]
        public async Task<IActionResult> CreateTask()
        {
            List<CategoryDto> list = new();
            var response = await _categoryService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CategoryDto>>(Convert.ToString(response.Result));
            }
            ViewBag.SelectList = new SelectList(list, "Id", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTask(TaskCreateDto taskDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _taskService.CreateAsync<APIResponse>(taskDto, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Task created successfully";
                    return RedirectToAction("Index");
                }
            }
            TempData["error"] = "Error";
            return View(taskDto);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteTask(int id)
        {
            var response = await _taskService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<TaskDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteTask(TaskDto taskDto)
        {
            var response = await _taskService.DeleteAsync<APIResponse>(taskDto.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Task deleted successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Error";
            return View(taskDto);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateTask(int id)
        {
            List<CategoryDto> list = new();
            var response2 = await _categoryService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (response2 != null && response2.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<CategoryDto>>(Convert.ToString(response2.Result));
            }
            var response = await _taskService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (response != null && response.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<TaskDto>(Convert.ToString(response.Result));
                TaskUpdateDto model2 = _mapper.Map<TaskUpdateDto>(model);
                model2.CategoryId = model.Category?.Id;
                ViewBag.SelectList = new SelectList(list, "Id","Name",model2.CategoryId);
                return View(model2);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Updatetask(TaskUpdateDto taskDto)
        {
            if (ModelState.IsValid)
            {
                APIResponse response = await _taskService.UpdateAsync<APIResponse>(taskDto, HttpContext.Session.GetString(SD.SessionToken));
                if (response != null && response.IsSuccess)
                {

                    TempData["success"] = "Task updated successfully";
                    return RedirectToAction("Index");
                }
            }
            TempData["error"] = "Error";
            return View(taskDto);
        }
    }
}

Task-Mangement-Web/Views/Shared/_Layout.cshtml
@using System_Utility
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task_Mangement_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task_Mangement_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                       
                        @if (httpAcc.HttpContext.Session.GetString(SD.SessionToken) != null &&
                            httpAcc.HttpContext.Session.GetString(SD.SessionToken).ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="IndexCategory">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {  
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                                </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2024 - Task_Mangement_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Task-Mangement-Web/Views/Shared/_Notification.cshtml
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["success"]!=null)
{
	<script>
		Swal.fire({
			position: "top-end",
			icon: "success",
			title: "@TempData["success"]",
			showConfirmButton: false,
			timer: 3000,
			timerProgressBar:true
		});
	</script>
}

@if (TempData["error"] != null)
{
	<script>
		Swal.fire({
			position: "top-end",
			icon: "error",
			title: "@TempData["error"]",
			showConfirmButton: false,
			timer: 3000,
			timerProgressBar: true
		});
	</script>
}